# Generated by Django 3.0 on 2023-10-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='address',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_link',
            field=models.URLField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='phone',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='working_hours',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
