# Generated by Django 3.0 on 2023-10-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20231012_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='working_hours',
            field=models.TextField(),
        ),
    ]
